### ISSUE TITLE
Update icon

### ISSUE THREAD

**Issue by webzunft** [webgilde/advanced-ads-visual-composer#7]
We are still using the old layout style for the icon. Should replace it with our [current logo](https://github.com/webgilde/advanced-ads/blob/master/admin/assets/img/tinymce-icon.png).

<img width="715" alt="Bildschirmfoto 2021-07-19 um 15 23 46" src="https://user-images.githubusercontent.com/2728720/126167480-1431da18-1be8-4fe3-8867-f91e77c5e463.png">

**Comment by alpipego** [comment]
Where can I find the new logo?
